# Site settings
title: Cosmo
description: Xiu-Fei Li
baseurl: "" 
url: "https://xiufeilee.github.io/lxf/" 

# GitHub User settings
username: xiufeilee
github_username: xiufeilee
user_description: A PhD candidate in physics
user_title: cosmo
email:  

# Blog Author settings
author:                  
  name:           Xiu-Fei Li
  picture:        
  email:          
  description:    cosmo
  twitter:
  facebook:
  github:          
  linkedin:


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  

permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
