# Site settings
title: Pointing to the Moon
description: Blog of Xiu-Fei Li
baseurl: "" 
url: "https://xiufeilee.github.io/lxf/" 

# GitHub User settings
username: Xiu-Fei Li
github_username: xiufeilee
user_description: A Physics undergrad with a broad interest
user_title: Physics Undergraduate
email: yingkai.liu@outlook.com

# Blog Author settings
author:
  name:           Xiu-Fei Li
  picture:        
  email:          yingkai.liu@outlook.com
  description:    I'm a Physics undergrad with a broad interest.
  twitter:
  facebook:
  github:         https://github.com/xiufeilee
  linkedin:


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  

permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      commentable: true
      status: Completed
      protected: false
      rss: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft"
